#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug  8 20:14:24 2019

@author: oswaldcodjoe
"""

#this is to practice for loops.

data = range(1,100,5)
multiples_of_two = []

for i in data:
    if i%2 == 0:
        multiples_of_two.append(i)
        
multiples_of_two

#Another example of for loops.
name = "Oswald Codjoe"
letters = []
for i in name:
    if i == "a":
        letters.append(i)
    elif i == "d":
        letters.append(i)
letters

